export enum QueryKeys {
  venuesDataQueryKey = 'VenuesData',
  venuesSearchQueryKey = 'VenuesSearchData',
  categoriesQueryKey = 'CategoriesData',
  venuesDataByCordsQueryKey = 'VenuesDataByCord',
  venuesDetailsDataQueryKey = 'VenuesDetailsData',
  venuesPlansDataQueryKey = 'VenuesPlasData',
  userSessionQueryKey = 'UserSession',
  userQueryKey = 'UserData',
  subscriptionsQueryKey = 'SubscriptionData',
  plansQueryKey = 'PlansData',
  paymentMethodsQueryKey = 'PaymentMethodsData',
  paymentGatewayTokenQueryKey = 'PaymentGatewayToken',
  favoritesQueryKey = 'favorites',
  venuesSearchBottomSheetQueryKey = 'VenuesDataBottomSheet',
  checkinQueryKey = 'ProfileCheckIn',
  classesSearchQueryKey = 'ClassesSearch',
  venueClassesQueryKey = 'VenueClasses',
  classDetailsQueryKey = 'ClassDetails',
  paymentSuccessQueryKey = 'PaymentSuccessData',
  paymentCreateSubQueryKey = 'PaymentSubData',
  schedulesDataQuerykey = 'SchedulesData',
}
